// Shared award definitions: [name, description, getter(profile, unlockedLevel), goal]
export const ACH = [
  ['FIRST BLOOD', 'Destroy 1 enemy', (p) => p.kills, 1],
  ['EXTERMINATOR', 'Destroy 500 enemies', (p) => p.kills, 500],
  ['BOSS HUNTER', 'Defeat 5 bosses', (p) => p.bosses, 5],
  ['BOSS SLAYER', 'Defeat 15 bosses', (p) => p.bosses, 15],
  ['SKILLED', 'Use skills 50 times', (p) => p.skills, 50],
  ['TREASURE HUNTER', 'Clear 3 bonus rounds', (p) => p.bonus, 3],
  ['HALFWAY THERE', 'Reach Space Impact level 5', (p, u) => u + 1, 5],
  ['EARTH SAVED', 'Beat Space Impact', (p) => p.spaceWins, 1],
  ['LIFE SAVER', 'Rescue 10 POWs', (p) => p.pows, 10],
  ['COMMANDO', 'Beat Operation Ground Zero', (p) => p.slugWins, 1],
  ['HIGH FLYER', 'Score 100,000 in Space Impact', (p) => p.spaceHi, 100000],
  ['FIRST WIN', 'Win a pickleball game', (p) => p.pickleWins || 0, 1],
  ['PICKLE PRO', 'Win 10 pickleball games', (p) => p.pickleWins || 0, 10],
  ['ACE SERVER', 'Serve 5 aces', (p) => p.aces || 0, 5],
  ['CARD SHARK', 'Win 5 card games', (p) => p.cardWins || 0, 5],
  ['UNO CHAMP', 'Win a UNO match', (p) => p.unoWins || 0, 1],
  ['BIG TWO', 'Win a Pusoy Dos match', (p) => p.pusoyWins || 0, 1],
  ['LUCKY NINE', 'Get a natural 9 in Lucky 9', (p) => p.luckyNines || 0, 1],
  ['TONG-ITS!', 'Empty your hand to win Tong-its', (p) => p.tongitsWins || 0, 1],
  ['CHOMPER', 'Eat 1000 dots in Maze Chomp', (p) => p.chompDots || 0, 1000],
  ['GHOST BUSTER', 'Eat 50 ghosts', (p) => p.chompGhosts || 0, 50],
  ['MAZE RUNNER', 'Clear 5 mazes', (p) => p.chompLevels || 0, 5],
  ['LINE CLEARER', 'Clear 100 lines in Tetra Blast', (p) => p.tetrisLines || 0, 100],
  ['TETRIS!', 'Clear 4 lines at once', (p) => p.tetrises || 0, 1],
  ['T-SPINNER', 'Land 5 T-spins', (p) => p.tspins || 0, 5],
  ['SPRINTER', 'Finish a 40-line Sprint', (p) => p.sprints || 0, 1],
  ['BATTLE WINNER', 'Win a Tetra Blast battle', (p) => p.tetrisWins || 0, 1],
  ['BOMBERMAN', 'Win a Bomber Blast match', (p) => p.bomberWins || 0, 1],
  ['DEMOLITION', 'Blow up 100 blocks', (p) => p.bricks || 0, 100],
  ['BOMB SQUAD', 'Knock out 10 opponents', (p) => p.bomberKills || 0, 10],
  ['SOLDIER', 'Score 50,000 in Ground Zero', (p) => p.slugHi, 50000],
]

export const awardProgress = (p, unlocked = 0) => ACH.map(([name, desc, get, goal]) => ({ name, desc, goal, value: Math.min(goal, get(p, unlocked)), done: get(p, unlocked) >= goal }))
