// Supplied logo art. Generated by scripts/import-logos.mjs.
export const GAME_ART = {
  "breaker": {
    "title": "Neon Breaker",
    "color": "#43d8ff",
    "covers": [
      {
        "src": "/art/logos/breaker-ec975b88-768.webp",
        "small": "/art/logos/breaker-ec975b88-320.webp",
        "width": 1254,
        "height": 1254,
        "edition": "Neon Breaker"
      }
    ]
  },
  "gems": {
    "title": "Gem Crush",
    "color": "#ffce44",
    "covers": [
      {
        "src": "/art/logos/gems-eaf058f9-768.webp",
        "small": "/art/logos/gems-eaf058f9-320.webp",
        "width": 1254,
        "height": 1254,
        "edition": "Gem Crush"
      }
    ]
  },
  "runner": {
    "title": "Neon Runner",
    "color": "#35daff",
    "covers": [
      {
        "src": "/art/logos/runner-bd3ee775-768.webp",
        "small": "/art/logos/runner-bd3ee775-320.webp",
        "width": 1254,
        "height": 1254,
        "edition": "Neon city"
      },
      {
        "src": "/art/logos/runner-9724449a-768.webp",
        "small": "/art/logos/runner-9724449a-320.webp",
        "width": 1254,
        "height": 1254,
        "edition": "City sprint"
      }
    ]
  },
  "orb": {
    "title": "Orb Rush",
    "color": "#42caff",
    "covers": [
      {
        "src": "/art/logos/orb-55a69b97-768.webp",
        "small": "/art/logos/orb-55a69b97-320.webp",
        "width": 1254,
        "height": 1254,
        "edition": "Orb Rush"
      }
    ]
  },
  "merge": {
    "title": "2048 Merge",
    "color": "#f5bd3d",
    "covers": [
      {
        "src": "/art/logos/merge-028ea924-768.webp",
        "small": "/art/logos/merge-028ea924-320.webp",
        "width": 1254,
        "height": 1254,
        "edition": "2048 Merge"
      }
    ]
  },
  "slice": {
    "title": "Slice Ninja",
    "color": "#ff643a",
    "covers": [
      {
        "src": "/art/logos/slice-939b87cd-768.webp",
        "small": "/art/logos/slice-939b87cd-320.webp",
        "width": 1254,
        "height": 1254,
        "edition": "Festival dojo"
      },
      {
        "src": "/art/logos/slice-49a4575c-768.webp",
        "small": "/art/logos/slice-49a4575c-320.webp",
        "width": 1254,
        "height": 1254,
        "edition": "Night dojo"
      }
    ]
  },
  "garden": {
    "title": "Garden Siege",
    "color": "#99e747",
    "covers": [
      {
        "src": "/art/logos/garden-394ec707-768.webp",
        "small": "/art/logos/garden-394ec707-320.webp",
        "width": 1254,
        "height": 1254,
        "edition": "Garden Siege"
      }
    ]
  },
  "td": {
    "title": "Neon Defense",
    "color": "#42d8ff",
    "covers": [
      {
        "src": "/art/logos/td-d6314e2b-768.webp",
        "small": "/art/logos/td-d6314e2b-320.webp",
        "width": 1254,
        "height": 1254,
        "edition": "Neon Defense"
      }
    ]
  },
  "rhythm": {
    "title": "Neon Beat",
    "color": "#f54bda",
    "covers": [
      {
        "src": "/art/logos/rhythm-17a9ed64-768.webp",
        "small": "/art/logos/rhythm-17a9ed64-320.webp",
        "width": 1254,
        "height": 1254,
        "edition": "Neon Beat"
      }
    ]
  },
  "ttt": {
    "title": "Tic-Tac-Toe",
    "color": "#ffbc3c",
    "covers": [
      {
        "src": "/art/logos/ttt-1d46c4f9-768.webp",
        "small": "/art/logos/ttt-1d46c4f9-320.webp",
        "width": 1254,
        "height": 1254,
        "edition": "Tic-Tac-Toe"
      }
    ]
  },
  "simon": {
    "title": "Color Memory",
    "color": "#f6d449",
    "covers": [
      {
        "src": "/art/logos/simon-bf78a835-768.webp",
        "small": "/art/logos/simon-bf78a835-320.webp",
        "width": 1254,
        "height": 1254,
        "edition": "Color Memory"
      }
    ]
  },
  "fruit": {
    "title": "Fruit Merge",
    "color": "#a8e85c",
    "covers": [
      {
        "src": "/art/logos/fruit-a35d3680-768.webp",
        "small": "/art/logos/fruit-a35d3680-320.webp",
        "width": 1254,
        "height": 1254,
        "edition": "Fruit Merge"
      }
    ]
  },
  "hunt": {
    "title": "13 Days of Hell",
    "color": "#e95845",
    "covers": [
      {
        "src": "/art/logos/hunt-9996de57-768.webp",
        "small": "/art/logos/hunt-9996de57-320.webp",
        "width": 1254,
        "height": 1254,
        "edition": "13 Days of Hell"
      }
    ]
  },
  "hoopclash": {
    "title": "Hoop Clash",
    "color": "#ffaf39",
    "covers": [
      {
        "src": "/art/logos/hoopclash-12cb069f-768.webp",
        "small": "/art/logos/hoopclash-12cb069f-320.webp",
        "width": 1254,
        "height": 1254,
        "edition": "Hoop Clash"
      }
    ]
  },
  "sumo": {
    "title": "Sumo Push",
    "color": "#ffb738",
    "covers": [
      {
        "src": "/art/logos/sumo-2eef7c76-768.webp",
        "small": "/art/logos/sumo-2eef7c76-320.webp",
        "width": 1254,
        "height": 1254,
        "edition": "Sumo Push"
      }
    ]
  },
  "skydash": {
    "title": "Sky Dash",
    "color": "#50d2ff",
    "covers": [
      {
        "src": "/art/logos/skydash-eb6528c4-768.webp",
        "small": "/art/logos/skydash-eb6528c4-320.webp",
        "width": 1254,
        "height": 1254,
        "edition": "Sky Dash"
      }
    ]
  },
  "memory": {
    "title": "Memory Flip",
    "color": "#4edbcc",
    "covers": [
      {
        "src": "/art/logos/memory-1f65a742-768.webp",
        "small": "/art/logos/memory-1f65a742-320.webp",
        "width": 1254,
        "height": 1254,
        "edition": "Memory Flip"
      }
    ]
  },
  "topcard": {
    "title": "Top Players",
    "color": "#ffd544",
    "covers": [
      {
        "src": "/art/logos/topcard-108c9f93-768.webp",
        "small": "/art/logos/topcard-108c9f93-320.webp",
        "width": 1254,
        "height": 1254,
        "edition": "Top Players"
      }
    ]
  },
  "brand": {
    "title": "My Space Arcade",
    "color": "#65dfff",
    "covers": [
      {
        "src": "/art/logos/brand-7e658724-768.webp",
        "small": "/art/logos/brand-7e658724-320.webp",
        "width": 2048,
        "height": 2048,
        "edition": "My Space Arcade"
      }
    ]
  },
  "wing": {
    "title": "Wing Dash",
    "color": "#57d9f5",
    "covers": [
      {
        "src": "/art/logos/wing-1b71a032-768.webp",
        "small": "/art/logos/wing-1b71a032-320.webp",
        "width": 2048,
        "height": 2048,
        "edition": "Wing Dash"
      }
    ]
  },
  "mini": {
    "title": "Mini Games",
    "color": "#bd61ff",
    "covers": [
      {
        "src": "/art/logos/mini-a688ff5e-768.webp",
        "small": "/art/logos/mini-a688ff5e-320.webp",
        "width": 2048,
        "height": 2048,
        "edition": "Mini Games"
      }
    ]
  },
  "empire": {
    "title": "Empire Rise",
    "color": "#edbd42",
    "covers": [
      {
        "src": "/art/logos/empire-bff86fed-768.webp",
        "small": "/art/logos/empire-bff86fed-320.webp",
        "width": 1254,
        "height": 1254,
        "edition": "Empire Rise"
      }
    ]
  },
  "fight": {
    "title": "Iron Fists",
    "color": "#ff5476",
    "covers": [
      {
        "src": "/art/logos/fight-4eabe018-768.webp",
        "small": "/art/logos/fight-4eabe018-320.webp",
        "width": 2048,
        "height": 2048,
        "edition": "Iron Fists"
      }
    ]
  },
  "rogue": {
    "title": "Neon Depths",
    "color": "#bf57ff",
    "covers": [
      {
        "src": "/art/logos/rogue-359d8686-768.webp",
        "small": "/art/logos/rogue-359d8686-320.webp",
        "width": 2048,
        "height": 2048,
        "edition": "Neon Depths"
      }
    ]
  },
  "cards": {
    "title": "Card Room",
    "color": "#59e3ae",
    "covers": [
      {
        "src": "/art/logos/cards-14c915bc-768.webp",
        "small": "/art/logos/cards-14c915bc-320.webp",
        "width": 1254,
        "height": 1254,
        "edition": "Card Room"
      }
    ]
  },
  "chomp": {
    "title": "Maze Chomp",
    "color": "#ffda47",
    "covers": [
      {
        "src": "/art/logos/chomp-80c0c185-768.webp",
        "small": "/art/logos/chomp-80c0c185-320.webp",
        "width": 1254,
        "height": 1254,
        "edition": "Maze Chomp"
      }
    ]
  },
  "archery": {
    "title": "Archery",
    "color": "#39d9ff",
    "covers": [
      {
        "src": "/art/logos/archery-e4997b03-768.webp",
        "small": "/art/logos/archery-e4997b03-320.webp",
        "width": 1254,
        "height": 1254,
        "edition": "Forest range"
      },
      {
        "src": "/art/logos/archery-26186253-768.webp",
        "small": "/art/logos/archery-26186253-320.webp",
        "width": 1254,
        "height": 1254,
        "edition": "Neon target"
      }
    ]
  },
  "space": {
    "title": "Space Impact: Neon",
    "color": "#3ed7ff",
    "covers": [
      {
        "src": "/art/logos/space-240b32d3-768.webp",
        "small": "/art/logos/space-240b32d3-320.webp",
        "width": 1254,
        "height": 1254,
        "edition": "Starfighter"
      },
      {
        "src": "/art/logos/space-edfdc212-768.webp",
        "small": "/art/logos/space-edfdc212-320.webp",
        "width": 1254,
        "height": 1254,
        "edition": "Rocket"
      }
    ]
  },
  "tetris": {
    "title": "Tetra Blast",
    "color": "#c26aff",
    "covers": [
      {
        "src": "/art/logos/tetris-dc0a8f30-768.webp",
        "small": "/art/logos/tetris-dc0a8f30-320.webp",
        "width": 2048,
        "height": 2048,
        "edition": "Tetra Blast"
      }
    ]
  },
  "hockey": {
    "title": "Air Hockey",
    "color": "#4de0f2",
    "covers": [
      {
        "src": "/art/logos/hockey-34d684d7-768.webp",
        "small": "/art/logos/hockey-34d684d7-320.webp",
        "width": 2048,
        "height": 2048,
        "edition": "Air Hockey"
      }
    ]
  },
  "hoops": {
    "title": "Hoop Shot",
    "color": "#ffb848",
    "covers": [
      {
        "src": "/art/logos/hoops-d9fa2c98-768.webp",
        "small": "/art/logos/hoops-d9fa2c98-320.webp",
        "width": 2048,
        "height": 2048,
        "edition": "Hoop Shot"
      }
    ]
  },
  "c4": {
    "title": "Connect Four",
    "color": "#47dfff",
    "covers": [
      {
        "src": "/art/logos/c4-74702e5d-768.webp",
        "small": "/art/logos/c4-74702e5d-320.webp",
        "width": 2048,
        "height": 2048,
        "edition": "Connect Four"
      }
    ]
  },
  "ocean": {
    "title": "Ocean Hunter",
    "color": "#46d5ef",
    "covers": [
      {
        "src": "/art/logos/ocean-8ed1ece3-768.webp",
        "small": "/art/logos/ocean-8ed1ece3-320.webp",
        "width": 1254,
        "height": 1254,
        "edition": "Ocean Hunter"
      }
    ]
  },
  "flames": {
    "title": "FLAMES",
    "color": "#ff5ab7",
    "covers": [
      {
        "src": "/art/logos/flames-57d1f75a-768.webp",
        "small": "/art/logos/flames-57d1f75a-320.webp",
        "width": 2048,
        "height": 2048,
        "edition": "FLAMES"
      }
    ]
  },
  "pickle": {
    "title": "Pickleball",
    "color": "#ffdf51",
    "covers": [
      {
        "src": "/art/logos/pickle-1a48e363-768.webp",
        "small": "/art/logos/pickle-1a48e363-320.webp",
        "width": 1254,
        "height": 1254,
        "edition": "Pickleball"
      }
    ]
  },
  "race": {
    "title": "Turbo Rush",
    "color": "#ffbc35",
    "covers": [
      {
        "src": "/art/logos/race-02642bb8-768.webp",
        "small": "/art/logos/race-02642bb8-320.webp",
        "width": 1254,
        "height": 1254,
        "edition": "Turbo Rush"
      }
    ]
  },
  "pool": {
    "title": "Billiards",
    "color": "#8bdd5b",
    "covers": [
      {
        "src": "/art/logos/pool-bcb7b946-768.webp",
        "small": "/art/logos/pool-bcb7b946-320.webp",
        "width": 1254,
        "height": 1254,
        "edition": "Billiards"
      }
    ]
  },
  "knife": {
    "title": "Knife Hit",
    "color": "#ffbd44",
    "covers": [
      {
        "src": "/art/logos/knife-e42b67bb-768.webp",
        "small": "/art/logos/knife-e42b67bb-320.webp",
        "width": 1254,
        "height": 1254,
        "edition": "Knife Hit"
      }
    ]
  },
  "kart": {
    "title": "Kart Rush",
    "color": "#ffd84e",
    "covers": [
      {
        "src": "/art/logos/kart-3fd45042-768.webp",
        "small": "/art/logos/kart-3fd45042-320.webp",
        "width": 1254,
        "height": 1254,
        "edition": "Kart Rush"
      }
    ]
  },
  "mines": {
    "title": "Mine Sweep",
    "color": "#ffc34a",
    "covers": [
      {
        "src": "/art/logos/mines-7643af39-768.webp",
        "small": "/art/logos/mines-7643af39-320.webp",
        "width": 1254,
        "height": 1254,
        "edition": "Mine explorer"
      },
      {
        "src": "/art/logos/mines-5acc15e1-768.webp",
        "small": "/art/logos/mines-5acc15e1-320.webp",
        "width": 1254,
        "height": 1254,
        "edition": "Crystal mine"
      }
    ]
  },
  "miner": {
    "title": "Idle Miner",
    "color": "#ffbf45",
    "covers": [
      {
        "src": "/art/logos/miner-999df977-768.webp",
        "small": "/art/logos/miner-999df977-320.webp",
        "width": 1254,
        "height": 1254,
        "edition": "Idle Miner"
      }
    ]
  },
  "bubble": {
    "title": "Bubble Pop",
    "color": "#4bdcf7",
    "covers": [
      {
        "src": "/art/logos/bubble-71c4d250-768.webp",
        "small": "/art/logos/bubble-71c4d250-320.webp",
        "width": 1254,
        "height": 1254,
        "edition": "Bubble Pop"
      }
    ]
  },
  "ssx": {
    "title": "Snow Rush",
    "color": "#71d5ff",
    "covers": [
      {
        "src": "/art/logos/ssx-80c7d33d-768.webp",
        "small": "/art/logos/ssx-80c7d33d-320.webp",
        "width": 1254,
        "height": 1254,
        "edition": "Snow Rush"
      }
    ]
  },
  "fishing": {
    "title": "Lake Fishing",
    "color": "#50dce3",
    "covers": [
      {
        "src": "/art/logos/fishing-f1765c62-768.webp",
        "small": "/art/logos/fishing-f1765c62-320.webp",
        "width": 1254,
        "height": 1254,
        "edition": "Lake Fishing"
      }
    ]
  },
  "kong": {
    "title": "Girder Gorilla",
    "color": "#ffb03f",
    "covers": [
      {
        "src": "/art/logos/kong-9371324f-768.webp",
        "small": "/art/logos/kong-9371324f-320.webp",
        "width": 1254,
        "height": 1254,
        "edition": "Girder Gorilla"
      }
    ]
  },
  "snake": {
    "title": "Neon Snake",
    "color": "#85ec46",
    "covers": [
      {
        "src": "/art/logos/snake-b6b0457e-768.webp",
        "small": "/art/logos/snake-b6b0457e-320.webp",
        "width": 1254,
        "height": 1254,
        "edition": "Neon Snake"
      }
    ]
  },
  "traffic": {
    "title": "Traffic Dodge",
    "color": "#ffc742",
    "covers": [
      {
        "src": "/art/logos/traffic-19ed408a-768.webp",
        "small": "/art/logos/traffic-19ed408a-320.webp",
        "width": 1254,
        "height": 1254,
        "edition": "City chase copy"
      }
    ]
  },
  "word": {
    "title": "Word Hunt",
    "color": "#e790d0",
    "covers": [
      {
        "src": "/art/logos/word-7ac66f46-768.webp",
        "small": "/art/logos/word-7ac66f46-320.webp",
        "width": 560,
        "height": 560,
        "edition": "Word Hunt"
      }
    ]
  },
  "mole": {
    "title": "Mole Smash",
    "color": "#bade53",
    "covers": [
      {
        "src": "/art/logos/mole-ec353e88-768.webp",
        "small": "/art/logos/mole-ec353e88-320.webp",
        "width": 1254,
        "height": 1254,
        "edition": "Mole Smash"
      }
    ]
  },
  "stack": {
    "title": "Stack Tower",
    "color": "#ffc847",
    "covers": [
      {
        "src": "/art/logos/stack-7f3133d8-768.webp",
        "small": "/art/logos/stack-7f3133d8-320.webp",
        "width": 1254,
        "height": 1254,
        "edition": "Stack Tower"
      }
    ]
  },
  "shipcard": {
    "title": "Customize Ship",
    "color": "#49d9ff",
    "covers": [
      {
        "src": "/art/logos/shipcard-e9e7ef4b-768.webp",
        "small": "/art/logos/shipcard-e9e7ef4b-320.webp",
        "width": 1254,
        "height": 1254,
        "edition": "Customize Ship"
      }
    ]
  },
  "climb": {
    "title": "Frost Climbers",
    "color": "#73d9ff",
    "covers": [
      {
        "src": "/art/logos/climb-1568be4e-768.webp",
        "small": "/art/logos/climb-1568be4e-320.webp",
        "width": 1254,
        "height": 1254,
        "edition": "Frost Climbers"
      }
    ]
  },
  "pong": {
    "title": "Pong Duel",
    "color": "#ec76e9",
    "covers": [
      {
        "src": "/art/logos/pong-892f288e-768.webp",
        "small": "/art/logos/pong-892f288e-320.webp",
        "width": 1254,
        "height": 1254,
        "edition": "Pong Duel"
      }
    ]
  }
}
