// Everything search engines (and link previews) should know about the arcade, in one place.
export const SITE = (process.env.NEXT_PUBLIC_SITE_URL || 'http://localhost:3000').replace(/\/+$/, '')
export const SITE_NAME = 'My Space Arcade'
export const SITE_DESC = 'Play 30+ free browser games with friends: FLAMES, Tetris-style blocks, 3D racing and kart battles, snowboarding, fighting, poker, Uno, Empire building, plants vs zombies style defence and more. No download, works on phone and PC, online multiplayer.'
export const SITE_KEYWORDS = ['free online games', 'browser games', 'multiplayer games', 'flames game', 'flames love calculator', 'arcade games', '3d browser games', 'play with friends', 'kart racing game', 'snowboard game', 'uno online', 'poker online', 'tong its', 'pusoy dos', 'lucky 9']

// slug -> the dashboard tab the game lives in (used by ?play=slug deep links)
export const GAMES = [
  { slug: 'flames', tab: 'flames', name: 'FLAMES', genre: 'Love and friendship game', tag: 'The classic FLAMES name game: Friends, Lovers, Affection, Marriage, Enemies or Siblings?', multi: false,
    desc: 'FLAMES is the classic paper game for finding out what two names add up to: Friends, Lovers, Affection, Marriage, Enemies or Siblings. Type two names and watch the letters cancel, count and eliminate, step by step, with animation and sound.',
    keys: ['flames game', 'flames love calculator', 'flames name game', 'flames game online', 'flames friends lovers affection marriage enemies siblings', 'name compatibility game'] },
  { slug: 'space-impact', tab: 'space', name: 'Space Impact: Neon', genre: 'Shoot-em-up', tag: '10 missions, 10 bosses and a squad of ships, co-op with friends.', multi: true, desc: 'A neon side-scrolling space shooter with 10 missions, 10 bosses, power-ups, a squad of three ships and online co-op.', keys: ['space shooter game', 'space impact online', 'neon shooter browser game'] },
  { slug: 'ground-zero', tab: 'slug', name: 'Operation Ground Zero', genre: 'Run and gun', tag: 'A pixel run-and-gun with vehicles, bosses and online score duels.', multi: true, desc: 'A run-and-gun action game with stages, vehicles, grenades, airstrikes, bosses and head-to-head score duels with a friend.', keys: ['run and gun game', 'metal slug style game online', 'shooting game browser'] },
  { slug: 'pickleball', tab: 'pickle', name: 'Pickleball', genre: 'Sports', tag: 'Real pickleball rules: first to 11, win by 2, online 1v1.', multi: true, desc: 'Pickleball with real scoring (first to 11, win by two), serves, dinks and smashes against bots, a friend on one keyboard, or online.', keys: ['pickleball game online', 'pickleball browser game'] },
  { slug: 'bomber-blast', tab: 'bomber', name: 'Bomber Blast', genre: 'Arcade battle', tag: 'Drop bombs, blow up crates, outlast 3 rivals.', multi: true, desc: 'A Bomberman-style arena: drop bombs, break crates, grab power-ups and outlast up to three rivals, friends or bots.', keys: ['bomberman style game online', 'bomb arena multiplayer'] },
  { slug: 'tetra-blast', tab: 'tetris', name: 'Tetra Blast', genre: 'Puzzle', tag: 'Falling blocks, garbage attacks and 1v1 online battles.', multi: true, desc: 'A falling-block puzzle game with hold, ghost piece, combos and a 1v1 battle mode where cleared lines send garbage to your opponent.', keys: ['tetris online multiplayer', 'falling blocks game', 'block puzzle game online'] },
  { slug: 'maze-chomp', tab: 'chomp', name: 'Maze Chomp', genre: 'Arcade', tag: 'Eat the pellets, dodge the ghosts, co-op and ghost modes.', multi: true, desc: 'A maze chase in the style of the arcade classic: eat pellets and fruit, use power pellets on the ghosts, or play the ghost yourself.', keys: ['pac man style game', 'maze chase game online'] },
  { slug: 'card-room', tab: 'cards', name: 'Card Room: Uno, Poker, Baccarat, Tong-its, Pusoy Dos, Lucky 9', genre: 'Card games', tag: 'Six card games with bots or friends online.', multi: true, desc: 'A card room with Uno, Pusoy Dos, Lucky 9, Tong-its, Baccarat and Texas Hold\'em poker. Play against smart bots or up to four friends online.', keys: ['uno online', 'poker online free', 'tong its online', 'pusoy dos online', 'lucky 9 online', 'baccarat online', 'texas holdem browser'] },
  { slug: 'turbo-rush', tab: 'race', name: 'Turbo Rush and Kart Clash', genre: '3D racing', tag: '3D racing with drifting, nitro and a kart mode with items, plus day, night and weather.', multi: true, desc: 'Race 5 tracks in 3D with drifting, mini-turbos and nitro, or switch on Kart items: bananas, homing shells, stars and lightning. Day and night cycles and weather change while you race. Up to four players online.', keys: ['3d racing game online', 'kart racing game browser', 'mario kart style game', 'drift racing game'] },
  { slug: 'iron-fists', tab: 'fight', name: 'Iron Fists', genre: '3D fighting', tag: '40 fighters, supers and FINISH HIM finishers, online 1v1.', multi: true, desc: 'A 3D fighting game with 40 fighters across 10 styles and 4 elements, specials, cinematic supers and element finishers. Play bots, a friend, or online.', keys: ['3d fighting game online', 'mortal kombat style game', 'fighting game browser'] },
  { slug: 'air-hockey', tab: 'hockey', name: 'Air Hockey', genre: 'Sports', tag: 'Fast neon air hockey, first to 7.', multi: true, desc: 'Neon air hockey with chaos power-ups, bots and online 1v1.', keys: ['air hockey online'] },
  { slug: 'billiards', tab: 'pool', name: 'Billiards', genre: 'Sports', tag: '8-ball pool with spin, bots and online 1v1.', multi: true, desc: '8-ball pool with real physics, spin and bank shots against a bot or a friend online.', keys: ['8 ball pool online', 'billiards browser game'] },
  { slug: 'frost-climbers', tab: 'climb', name: 'Frost Climbers', genre: '3D platformer', tag: 'Climb icy mountains, smash the ice above you, co-op for two.', multi: true, desc: 'A 3D ice-climbing platformer: jump up into the ice to smash a hole, climb through it, hammer yetis and birds, dodge icicles and reach the summit of eight mountains. One or two climbers, same keyboard or online.', keys: ['ice climber game online', 'ice climbers style game', 'mountain climbing platformer', '2 player platformer browser'] },
  { slug: 'girder-gorilla', tab: 'kong', name: 'Girder Gorilla', genre: '3D platformer', tag: 'Jump the barrels, climb the girders, rescue the captive. Up to 20x wider.', multi: true, desc: 'A 3D barrel-jumping climb in the spirit of the classic giant-ape arcade game: run sloping girders, climb ladders, hammer the barrels and rescue the captive. Choose girder widths up to 20 times wider, with minimap. Co-op for two.', keys: ['donkey kong style game online', 'barrel jumping game', 'ladder platformer browser game'] },
  { slug: 'neon-defense', tab: 'td', name: 'Neon Defense', genre: 'Tower defence', tag: 'Build towers, hold the road, call airstrikes.', multi: true, desc: 'A tower defence game with several maps, upgrades, airstrikes and a story mode, plus a head-to-head score duel.', keys: ['tower defense game online', 'tower defence browser'] },
  { slug: 'neon-depths', tab: 'rogue', name: 'Neon Depths', genre: '3D roguelike', tag: 'A haunted-forest roguelike with co-op, pets, a 50-room Abyss and huge maps.', multi: true, desc: 'A 3D roguelike through a haunted forest: heroes, races, evolving companions, weapons, powers, secrets, a 50-room Abyss and fighting rooms up to 20 times wider. Co-op for up to three.', keys: ['roguelike game online', 'dungeon crawler browser', 'co-op roguelike'] },
  { slug: 'neon-beat', tab: 'rhythm', name: 'Neon Beat', genre: 'Rhythm', tag: 'Four lanes, five songs, hold notes.', multi: true, desc: 'A four-lane rhythm game with five songs, hold notes, combos and grades, plus online score duels.', keys: ['rhythm game online', 'beat game browser'] },
  { slug: 'word-hunt', tab: 'word', name: 'Word Hunt', genre: 'Word puzzle', tag: 'Guess the 5-letter word in English or Filipino.', multi: true, desc: 'A five-letter word guessing game in English or Filipino with a daily word, hard mode and a head-to-head duel on the same word.', keys: ['wordle style game', 'word guessing game', 'filipino word game'] },
  { slug: '2048-merge', tab: 'merge', name: '2048 Merge', genre: 'Puzzle', tag: 'Slide and merge tiles, with undo and hammer.', multi: true, desc: 'The sliding tile puzzle with undo, hammer and shuffle helpers, three board sizes and online score duels.', keys: ['2048 game online'] },
  { slug: 'connect-four', tab: 'c4', name: 'Connect Four', genre: 'Board game', tag: 'Drop discs, line up four, online 1v1.', multi: true, desc: 'Connect Four against a bot, a friend on one device or online.', keys: ['connect 4 online'] },
  { slug: 'neon-snake', tab: 'snake', name: 'Neon Snake', genre: 'Arcade', tag: 'Solo, vs bot or 2 players.', multi: true, desc: 'A neon snake game with golden apples, rocks, a bot opponent, two-player mode and online duels.', keys: ['snake game online'] },
  { slug: 'neon-breaker', tab: 'breaker', name: 'Neon Breaker', genre: 'Arcade', tag: 'Brick breaking with power-ups.', multi: true, desc: 'A brick breaker with five levels, multi-ball, wide paddle and slow-ball power-ups.', keys: ['brick breaker online', 'breakout game'] },
  { slug: 'mine-sweep', tab: 'mines', name: 'Mine Sweep', genre: 'Puzzle', tag: 'Flags, chording and a race on the same minefield.', multi: true, desc: 'Minesweeper with three board sizes, flags, chording and an online race on the same minefield.', keys: ['minesweeper online'] },
  { slug: 'empire-rise', tab: 'empire', name: 'Empire Rise', genre: 'Strategy', tag: 'Grow a village into an empire on maps up to 1,920 tiles wide.', multi: true, desc: 'A 3D real-time strategy game: build a village, train soldiers, defend against raiders, and conquer rival kingdoms or build the Wonder. Map sizes up to 20 times wider, day and night, and weather. Up to four players.', keys: ['rts game browser', 'city builder game online', 'age of empires style game'] },
  { slug: 'snow-rush', tab: 'ssx', name: 'Snow Rush', genre: '3D snowboarding', tag: 'SSX-style snowboarding: tricks, rails, boost and huge mountains.', multi: true, desc: 'A 3D snowboarding game: race five riders or chase a trick score, hit kickers, grind rails and fill your boost with tricks. Mountains up to 20 times wider, with day, night and snow. Online racing for up to four.', keys: ['snowboarding game online', 'ssx style game', '3d snowboard browser game'] },
  { slug: 'orb-rush', tab: 'orb', name: 'Orb Rush', genre: 'Marble shooter', tag: 'Zuma-style marble shooting with 10 levels and online versus.', multi: true, desc: 'A marble-shooter: aim the frog, match three or more orbs and stop the chain reaching the skull. Ten levels, power orbs and online versus.', keys: ['zuma style game', 'marble shooter online'] },
  { slug: 'garden-siege', tab: 'garden', name: 'Garden Siege', genre: 'Lane defence', tag: 'Plants vs zombies style: defend the garden or lead the horde.', multi: true, desc: 'A lane-defence game: plant sunflowers and shooters to stop the zombie horde, lead the zombies yourself, or play online with one friend as the garden and the other as the horde.', keys: ['plants vs zombies style game', 'lane defense game online'] },
  { slug: '13-days-of-hell', tab: 'hunt', name: '13 Days of Hell', genre: 'Horror survival', tag: 'Survive 13 nights, watch your back. Co-op for 3.', multi: true, desc: 'A top-down horror survival game in a huge haunted forest: survive 13 nights, shop at dawn, and watch your back for stalkers. Or play Watch Your Back, one endless night. Co-op for up to three hunters.', keys: ['horror survival game browser', 'co-op survival game online', 'zombie survival game'] },
]
export const bySlug = (s) => GAMES.find((g) => g.slug === s)

export const FLAMES_FAQ = [
  ['What does FLAMES stand for?', 'FLAMES stands for Friends, Lovers, Affection, Marriage, Enemies and Siblings. It is a traditional paper game played with two names.'],
  ['How does the FLAMES game work?', 'Write both names, cross out the letters they share, count the letters left, then count around the word FLAMES crossing out one letter each time until a single letter remains. That letter is the answer.'],
  ['Is the FLAMES game accurate?', 'No. FLAMES is just for fun. It cannot tell you anything real about a relationship.'],
  ['Can I play FLAMES online for free?', 'Yes. Open My Space Arcade in your browser and choose FLAMES. It is free, needs no download and works on phones and computers.'],
]
