// Preserve each supplied composition; resize/encode only. Original files stay untouched.
import fs from 'node:fs/promises'
import path from 'node:path'
import { createHash } from 'node:crypto'
import sharp from 'sharp'
const sourceDir = process.argv[2]
if (!sourceDir) throw new Error('Usage: node scripts/import-logos.mjs /path/to/Logos')
const sources = JSON.parse(await fs.readFile('assets/logo-sources.json','utf8'))
const out = 'public/art/logos'
await fs.mkdir(out,{recursive:true})
const seen = new Map(), games = {}, inventory = []
for (const item of sources) {
  const input = await fs.readFile(path.join(sourceDir,item.source))
  const hash = createHash('sha256').update(input).digest('hex')
  let asset = seen.get(hash)
  if (!asset) {
    const stem = item.game+'-'+hash.slice(0,8)
    for (const size of [320,768]) await sharp(input).rotate().resize(size,size,{fit:'inside',withoutEnlargement:true}).webp({quality:90,effort:5}).toFile(`${out}/${stem}-${size}.webp`)
    const metadata = await sharp(input).metadata()
    asset = {src:`/art/logos/${stem}-768.webp`,small:`/art/logos/${stem}-320.webp`,width:metadata.width,height:metadata.height,edition:item.edition}
    seen.set(hash,asset)
  }
  const entry = games[item.game] ||= {title:item.title,color:item.color,covers:[]}
  if (!entry.covers.some(c=>c.src===asset.src)) entry.covers.push(asset)
  inventory.push({...item,sha256:hash,asset:asset.src})
}
// The richly illustrated variants lead; earlier editions remain selectable.
for (const id of ['runner','slice','space','archery','mines']) games[id].covers.reverse()
await fs.writeFile('src/game/branding.js','// Supplied logo art. Generated by scripts/import-logos.mjs.\nexport const GAME_ART = '+JSON.stringify(games,null,2)+'\n')
await fs.writeFile('assets/logo-inventory.json',JSON.stringify(inventory,null,2)+'\n')
console.log(`${sources.length} source files → ${seen.size} unique covers for ${Object.keys(games).length} games/screens.`)

const brandInput=path.join(sourceDir,sources.find(item=>item.game==='brand').source)
await sharp(brandInput).resize(512,512,{fit:'contain',background:'#080e20'}).png().toFile('src/app/icon.png')
await sharp(brandInput).resize(180,180,{fit:'contain',background:'#080e20'}).png().toFile('src/app/apple-icon.png')
